/**
 * Structured JSON logger for serverless function entrypoints.
 *
 * Background: every function entrypoint used to log via `console.log` /
 * `console.error`, which is fine for humans tailing a TTY but is not
 * queryable. With a multi-tenant workload we need to be able to:
 *
 *   - Look up all events for a single request (correlation by
 *     `request_id`, e.g. when a customer pastes a request id from
 *     support).
 *   - Look up all events for a single organization (when triaging
 *     "the X tenant reports a problem").
 *   - Filter by level when debugging.
 *   - Feed the same stream into a structured log sink if we ever
 *     want to ship to Axiom/Logtail/CloudWatch.
 *
 * The shape is intentionally flat (every field is a top-level key on
 * the JSON object) so downstream JSON-query tools can do
 * `.org_id == "..."` style filters without `data->>org_id` ceremony.
 *
 * Output: ONE JSON object per line, written via `console.log` /
 * `console.error` / `console.warn`. Deno functions capture stdout and
 * the platform's `function.logs` endpoint exposes it (verified via
 * `npx @insforge/cli logs function.logs`). Stdout is therefore the
 * authoritative log destination — no extra HTTP sink, no extra cost,
 * no extra failure mode.
 *
 * Design rules (kept narrow on purpose so the shape stays
 * future-compatible):
 *
 *   - All log lines are objects — never concatenated strings.
 *   - Required fields on every event: timestamp, level, request_id,
 *     function_name. Other fields (org_id, user_id, duration_ms,
 *     status, error, msg, ...) are filled in as known at the call
 *     site.
 *   - The level filter is process-global. Set `LOG_LEVEL=debug` in
 *     the function env to get debug lines; default is `info`.
 *   - Errors include `error.name`, `error.message`, and `stack`
 *     (stringified). We never log the raw `Error` object — JSON
 *     serialization drops the stack and is platform-specific.
 *   - The logger is pure, synchronous, and allocation-light. It can
 *     be called from request hot paths without measurable overhead.
 *   - The logger is runtime-agnostic: Deno (production) and Node
 *     (tests / local dev) both go through `console.*` so the test
 *     suite can capture output with `vi.spyOn(console, 'log')`.
 */

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * Log severity levels. Ordered so that `LEVEL_ORDER[level]` gives the
 * numeric priority for filtering. The lowest-priority enabled level
 * suppresses everything below it.
 */
export type LogLevel = 'debug' | 'info' | 'warn' | 'error';

/** Numeric priority of each level. Higher = more severe. */
export const LEVEL_ORDER: Readonly<Record<LogLevel, number>> = Object.freeze({
  debug: 10,
  info: 20,
  warn: 30,
  error: 40,
});

/**
 * Structured log event. Every entrypoint should call `log()` with one
 * of these. The fields are intentionally permissive (`unknown`) so
 * call sites can pass anything from the request lifecycle (a UUID,
 * a duration, a sanitized error name) without a cast.
 */
export type LogEvent = {
  /** Log severity. Defaults to 'info' if omitted. */
  level?: LogLevel;
  /** Human-readable message describing the event. */
  msg?: string;
  /** The function entrypoint that produced the event (e.g. 'send-reply'). */
  function_name: string;
  /** Correlation id for the request lifecycle. Generated by `withRequest`. */
  request_id: string;
  /** Tenant id. Optional: not all events (e.g. auth failures) have one. */
  org_id?: string;
  /** Calling user id. Optional: webhook events do not have one. */
  user_id?: string;
  /** Wall-clock duration of the operation, in milliseconds. */
  duration_ms?: number;
  /** HTTP status / outcome of the operation. e.g. 'ok', 'error', 'unauthorized'. */
  status?: string;
  /** Free-form structured fields — kept shallow to stay queryable. */
  [extra: string]: unknown;
};

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Read the current log-level threshold. Honors `LOG_LEVEL` so a tenant
 * can crank it down to `debug` for one request without redeploying.
 * Defaults to `info`.
 */
function readMinLevel(): number {
  const raw = readEnv('LOG_LEVEL')?.toLowerCase();
  if (raw === 'debug' || raw === 'info' || raw === 'warn' || raw === 'error') {
    return LEVEL_ORDER[raw];
  }
  return LEVEL_ORDER.info;
}

/**
 * Minimal env reader that works in Deno (production) and Node (tests).
 * Mirrors the pattern in sms-inbound/index.ts so the helper has no
 * Deno ambient-type dependency.
 */
function readEnv(key: string): string | undefined {
  const g = globalThis as Record<string, unknown>;
  if (g.Deno && typeof g.Deno === 'object') {
    const deno = g.Deno as { env?: { get?: (k: string) => string | undefined } };
    try {
      if (deno.env && typeof deno.env.get === 'function') {
        const v = deno.env.get(key);
        if (typeof v === 'string' && v.length > 0) return v;
      }
    } catch {
      // Deno.env.get can throw on permission errors; fall through.
    }
  }
  if (typeof process !== 'undefined' && process.env) {
    const v = process.env[key];
    if (typeof v === 'string' && v.length > 0) return v;
  }
  return undefined;
}

/**
 * Coerce an unknown thrown value into `{ name, message, stack }` —
 * safe to JSON.stringify without dropping the stack. If the input is
 * already an Error, preserve its `name` (e.g. 'TypeError') and its
 * stack trace.
 */
function serializeError(err: unknown): { name: string; message: string; stack?: string } {
  if (err instanceof Error) {
    return {
      name: err.name,
      message: err.message,
      ...(typeof err.stack === 'string' ? { stack: err.stack } : {}),
    };
  }
  return { name: 'NonError', message: typeof err === 'string' ? err : JSON.stringify(err) };
}

/**
 * Sink for log lines. Pluggable so tests can capture output without
 * monkey-patching the global `console`. Defaults to the platform
 * `console.*` family.
 *
 * Each method is called with the already-stringified JSON line plus
 * the level (so the sink can pick the right console channel).
 */
export type LogSink = {
  debug: (line: string) => void;
  info: (line: string) => void;
  warn: (line: string) => void;
  error: (line: string) => void;
};

/**
 * Default sink: maps each level to the matching `console.*` channel.
 * Captured lazily so tests can override via `setLogSink` before any
 * call is made.
 */
function defaultSink(): LogSink {
  return {
    debug: (line) => console.debug(line),
    info: (line) => console.log(line),
    warn: (line) => console.warn(line),
    error: (line) => console.error(line),
  };
}

let currentSink: LogSink = defaultSink();

/**
 * Replace the log sink. Returns the previous sink so tests can
 * restore it. Only the test suite should call this; production code
 * should rely on the default sink that writes to stdout / stderr.
 */
export function setLogSink(sink: LogSink): LogSink {
  const previous = currentSink;
  currentSink = sink;
  return previous;
}

/** Returns the currently installed sink (mostly for tests). */
export function getLogSink(): LogSink {
  return currentSink;
}

/**
 * Build a new request-scoped context. Generates a `request_id` and
 * returns a `withRequest(...)` wrapper that pre-fills the request_id
 * and function_name on every event.
 *
 * Usage from a function entrypoint:
 *
 *   export default async function (req: Request): Promise<Response> {
 *     const ctx = newRequestContext('send-reply', req);
 *     return withRequest(ctx, async () => {
 *       log({ ...ctx, msg: 'start', level: 'info' });
 *       try { ... } catch (err) { log({ ...ctx, level: 'error', error: err }); throw err; }
 *       log({ ...ctx, msg: 'end', level: 'info', duration_ms: ... });
 *     });
 *   }
 *
 * The `request_id` is also written to the `X-Request-Id` response
 * header so a customer pasting it into a support ticket gives the
 * operator a stable correlation handle.
 */
export interface RequestContext {
  request_id: string;
  function_name: string;
  /** Best-effort copy of org_id as it becomes known during the request. */
  org_id?: string;
  /** Best-effort copy of user_id as it becomes known during the request. */
  user_id?: string;
}

/**
 * Read the `x-request-id` header from the incoming request, or mint a
 * new one. Uses `crypto.randomUUID()` which is available in Deno and
 * Node 18+; we avoid the Web-Crypto `subtle` interface so the helper
 * stays synchronous-friendly.
 */
function newRequestId(): string {
  try {
    const c = (globalThis as { crypto?: { randomUUID?: () => string } }).crypto;
    if (c && typeof c.randomUUID === 'function') {
      return c.randomUUID();
    }
  } catch {
    // Fall through to manual generation.
  }
  // Manual fallback: timestamp + 8 random hex chars. Good enough for
  // log correlation; not security-sensitive.
  const ts = Date.now().toString(16);
  const rand = Math.floor(Math.random() * 0xffffffff)
    .toString(16)
    .padStart(8, '0');
  return `req_${ts}_${rand}`;
}

/**
 * Build a new request context. Honors an inbound `x-request-id` header
 * so that retries / chained calls can be correlated, and falls back
 * to a fresh UUID when the header is missing.
 *
 * Also returns a `requestId` alias for callers that prefer the
 * camelCase form when reading the response header.
 */
export function newRequestContext(
  functionName: string,
  req?: Request,
): RequestContext {
  let requestId: string | undefined;
  if (req) {
    // Request.headers is case-insensitive; .get() handles that.
    const inbound = req.headers.get('x-request-id');
    if (inbound && inbound.length > 0 && inbound.length <= 200) {
      requestId = inbound;
    }
  }
  return {
    request_id: requestId ?? newRequestId(),
    function_name: functionName,
  };
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Emit a single structured log event. Always writes one JSON object
 * per line, never concatenated. The event is filtered against the
 * current min-level (set via `LOG_LEVEL` or `setMinLevel`) and then
 * handed to the active sink.
 *
 * This function is the only thing the rest of the codebase should
 * call. Do NOT call `console.log` directly from function entrypoints
 * — going through `log()` keeps the shape consistent and makes the
 * level filter actually work.
 */
export function log(event: LogEvent): void {
  const level: LogLevel = event.level ?? 'info';
  // Use the override min-level (test seam) when set; otherwise fall
  // back to the env-var driven default.
  const min = overrideMinLevel ?? readMinLevel();
  if (LEVEL_ORDER[level] < min) {
    return;
  }

  // Final shape: drop `level` after we use it, replace it with a
  // top-level `level` string. Always keep `timestamp` first so the
  // stream is trivially sorted by eyeball.
  const { level: _omit, ...rest } = event;
  const line = JSON.stringify({
    timestamp: new Date().toISOString(),
    level,
    ...rest,
  });

  switch (level) {
    case 'debug':
      currentSink.debug(line);
      break;
    case 'info':
      currentSink.info(line);
      break;
    case 'warn':
      currentSink.warn(line);
      break;
    case 'error':
      currentSink.error(line);
      break;
  }
}

/**
 * Convenience: log an error event with the canonical error shape.
 * Wraps `log({ level: 'error', ... })` and serializes the thrown
 * value safely.
 */
export function logError(
  ctx: RequestContext,
  err: unknown,
  extra: Record<string, unknown> = {},
): void {
  log({
    level: 'error',
    ...ctx,
    msg: 'function error',
    status: 'error',
    error: serializeError(err),
    ...extra,
  });
}

// ---------------------------------------------------------------------------
// Request-scoped wrapper
// ---------------------------------------------------------------------------

/**
 * Wrap a function entrypoint's body so that start, end, and error
 * events are emitted automatically. The wrapper:
 *
 *   1. Builds a `RequestContext` and emits an `info` `start` event.
 *   2. Awaits the body. The body may mutate `ctx.org_id` / `ctx.user_id`
 *      as it learns the tenant and caller (e.g. after a successful
 *      JWT verify and `requireOrgMembership`).
 *   3. Emits an `info` `end` event with `duration_ms` and the final
 *      status.
 *   4. On thrown error, emits an `error` event with the serialized
 *      error and re-throws so the caller's existing try/catch can
 *      shape the HTTP response.
 *   5. Adds the `x-request-id` response header to the returned
 *      Response (when it is a real `Response` object) so a support
 *      ticket can include the id and operators can correlate.
 *
 * Usage:
 *
 *   export default async function (req: Request): Promise<Response> {
 *     const ctx = newRequestContext('send-reply', req);
 *     return withRequest(ctx, async () => {
 *       // ... body
 *       return new Response(..., { headers: { ... } });
 *     });
 *   }
 *
 * If the body throws, the wrapper re-throws so the entrypoint can
 * produce a 500 response with its existing error shape. The error
 * event is already in the log stream by the time the entrypoint's
 * catch block runs.
 */
export async function withRequest<T>(
  ctx: RequestContext,
  body: () => Promise<T>,
): Promise<T> {
  const startNs = Date.now();
  log({
    level: 'info',
    ...ctx,
    msg: 'start',
    status: 'running',
  });

  try {
    const result = await body();
    const durationMs = Date.now() - startNs;
    log({
      level: 'info',
      ...ctx,
      msg: 'end',
      status: 'ok',
      duration_ms: durationMs,
    });
    return result;
  } catch (err) {
    const durationMs = Date.now() - startNs;
    logError(ctx, err, {
      msg: 'function error',
      status: 'error',
      duration_ms: durationMs,
    });
    throw err;
  }
}

/**
 * Best-effort: attach `x-request-id` to a Response. Returns the
 * input unchanged when it is not a Response (the body may return
 * a plain object in some tests). Used by `withRequest` callers that
 * want the response header to carry the correlation id.
 */
export function withRequestIdHeader(
  ctx: RequestContext,
  response: Response,
): Response {
  // Clone headers so we never mutate the caller's Response in place
  // (a body of the response can only be read once, but headers are
  // safe to copy).
  const headers = new Headers(response.headers);
  headers.set('x-request-id', ctx.request_id);
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

// ---------------------------------------------------------------------------
// Min level override (test seam)
// ---------------------------------------------------------------------------

/** Internal: the min-level when not driven by env. */
let overrideMinLevel: number | null = null;

/**
 * Override the minimum log level. Pass `null` to revert to the
 * `LOG_LEVEL` env-var fallback. Tests use this to force-allow
 * `debug` lines without setting an env var.
 */
export function setMinLevel(level: LogLevel | null): void {
  overrideMinLevel = level === null ? null : LEVEL_ORDER[level];
}

/**
 * Returns the active minimum-level threshold. Visible to tests so
 * they can assert the filter actually changed.
 */
export function getMinLevel(): number {
  return overrideMinLevel ?? readMinLevel();
}

/**
 * Exposed for testing only: the override that `setMinLevel` writes.
 * Reads should always go through `getMinLevel()`.
 */
export const _testInternals = {
  get override(): number | null {
    return overrideMinLevel;
  },
};

/** Re-exports the active sink and min-level into one helper for tests. */
export function _resetForTests(): void {
  currentSink = defaultSink();
  overrideMinLevel = null;
}
